### ISSUE TITLE
【vlc-player】错误：翻译失败 , 错误提示（Invalid Access Limit）

### ISSUE THREAD

**Issue by FanXiangTM** [wxbool/video-srt-windows#1]
【vlc-player】错误：翻译失败 , 错误提示（Invalid Access Limit）

**Comment by wxbool** [comment]
请检查你的百度翻译接口设置，AppId、AppSecret 是否有效，百度翻译的服务是否成功开通

若仍无法处理，请联系个人QQ（2012210812）

**Comment by FanXiangTM** [comment]
@wxbool  这个AppId、AppSecret是一直在使用中的，在其他软件里可以正常使用

**Comment by wxbool** [comment]
这里使用的是 “通用翻译API” ，而且这个错误是 百度翻译 的接口返回的。

方便的话，你可以加我上面发的QQ，再详细看一下实际情况
