### ISSUE TITLE
根据教程做完所有操作后 遇到了问题

### ISSUE THREAD

**Issue by KleinerSource** [wxbool/video-srt-windows#14]
语音引擎翻译 则提示 错误：录音文件识别失败 , (识别内部通用错误，请稍候重试
字幕翻译则提示  错误：翻译失败！错误信息：SYSTEM ERROR   
 请问是哪里做错了么

**Comment by wxbool** [comment]
请检查两个方面：

1.生成字幕的媒体文件是否为正常的视频/音频文件？能否正常播放？纯背景音乐或人声不明显？
2.字幕翻译操作的SRT文件必须为UTF8的文件编码。

**Comment by KleinerSource** [comment]
测试过 了 翻译问题已经解决 的确是编码问题
但是语音引擎 我发现 50多M的音频文件  他看上去都没有上传(显示上传后立刻显示清除文件) 然后提示内部通用错误 而且oss短时间内看不到数据情况 我也不确定是否上传成功了

**Comment by wxbool** [comment]
软件提示上传成功就肯定是成功的。软件默认是会自动清理上传的临时文件。

建议你可以多换几个视频/音频文件进行尝试，我认为很可能是媒体文件的问题。
