### ISSUE TITLE
建议在教程中添加 OSS 生命周期，自动清理上传的文件

### ISSUE THREAD

**Issue by inkydragon** [wxbool/video-srt-windows#15]
- [生命周期规则介绍_文件生命周期_对象/文件（Object）_开发指南_对象存储 OSS-阿里云](https://help.aliyun.com/document_detail/31863.html?spm=5176.8466029.lifecycle.1.31921450rzNCsy)

轻度使用，这一堆 API 里面也就 OSS 需要付费了。
定期自动删除比较省心。
直接手动设置就行。

**Comment by wxbool** [comment]
0.2.9之后的版本，已经支持自动清理上传的临时文件了。
