### ISSUE TITLE
请问为什么需要用到oss服务呢

### ISSUE THREAD

**Issue by archi-git** [wxbool/video-srt-windows#21]
个人理解不是本地的文件直接请求api吗，为什么需要配置oss对象存储呢？

**Comment by wxbool** [comment]
你了解的比较少。

由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。

**Comment by archi-git** [comment]
> 你了解的比较少。
> 
> 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。

对这种中转技术很感兴趣，请问有相关技术文章可以分享吗

**Comment by patui** [comment]
> > 你了解的比较少。
> > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> 
> 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗

与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。

**Comment by wxbool** [comment]
。。。我真是服了！不懂就不要装懂，HTTP协议上传音频自然是没有问题，但是没有服务商会单纯直接用HTTP上传大文件然后就开始识别。你所说的讯飞，人家是通过HTTP切分成一个个小文件分片上传，再调用合并接口之后，服务端才开始进行识别任务，这种上传方式虽然可行，但明显更为繁琐。

阿里云这种，将音频上传至OSS临时保存，通过接口直接发起识别任务的明显更加简单。而且不仅仅是阿里云，Google、Azure、搜狗、百度 的录音转写都是这种技术方案。

**Comment by wxbool** [comment]
> > > 你了解的比较少。
> > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > 
> > 
> > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> 
> 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。

。。。我真是服了！不懂就不要装懂，HTTP协议上传音频自然是没有问题，但是没有服务商会单纯直接用HTTP上传大文件然后就开始识别。你所说的讯飞，人家是通过HTTP切分成一个个小文件分片上传，再调用合并接口之后，服务端才开始进行识别任务，这种上传方式虽然可行，但明显更为繁琐。

阿里云这种，将音频上传至OSS临时保存，通过接口直接发起识别任务的明显更加简单。而且不仅仅是阿里云，Google、Azure、搜狗、百度 的录音转写都是这种技术方案。

**Comment by wxbool** [comment]
> > > 你了解的比较少。
> > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > 
> > 
> > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> 
> 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。

而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
连这点费用都不想承担，那你闭嘴吧！

**Comment by patui** [comment]
> > > > 你了解的比较少。
> > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > 
> > > 
> > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > 
> > 
> > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> 
> 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> 连这点费用都不想承担，那你闭嘴吧！



> > > > 你了解的比较少。
> > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > 
> > > 
> > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > 
> > 
> > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> 
> 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> 连这点费用都不想承担，那你闭嘴吧！

我和你说技术，你和我说费用，完全胡说八道，还假装一本正经的，这和中转有毛关系，上传阿里云对象存储OSS不是走http协议吗? 不要误导和胡说八道。

**Comment by wxbool** [comment]
> > > > > 你了解的比较少。
> > > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > > 
> > > > 
> > > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > > 
> > > 
> > > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> > 
> > 
> > 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> > 连这点费用都不想承担，那你闭嘴吧！
> 
> > > > > 你了解的比较少。
> > > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > > 
> > > > 
> > > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > > 
> > > 
> > > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> > 
> > 
> > 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> > 连这点费用都不想承担，那你闭嘴吧！
> 
> 我和你说技术，你和我说费用，完全胡说八道，还假装一本正经的，这和中转有毛关系，上传阿里云对象存储OSS不是走http协议吗? 不要误导和胡说八道。

你跑到我这儿来秀什么？抠字眼？我有说没有用http协议吗？我说的中转就是利用OSS最为临时存储，有问题吗？而且费用也是你自己提出来的。

**Comment by patui** [comment]
> > > > > > 你了解的比较少。
> > > > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > > > 
> > > > > 
> > > > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > > > 
> > > > 
> > > > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> > > 
> > > 
> > > 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> > > 连这点费用都不想承担，那你闭嘴吧！
> > 
> > 
> > > > > > 你了解的比较少。
> > > > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > > > 
> > > > > 
> > > > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > > > 
> > > > 
> > > > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> > > 
> > > 
> > > 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> > > 连这点费用都不想承担，那你闭嘴吧！
> > 
> > 
> > 我和你说技术，你和我说费用，完全胡说八道，还假装一本正经的，这和中转有毛关系，上传阿里云对象存储OSS不是走http协议吗? 不要误导和胡说八道。
> 
> 你跑到我这儿来秀什么？抠字眼？我有说没有用http协议吗？我说的中转就是利用OSS最为临时存储，有问题吗？而且费用也是你自己提出来的。

你是讨论问题还是吵架?自己搞不清楚，反而来怪我指出问题本质原因?

**Comment by wxbool** [comment]
> > > > > > > 你了解的比较少。
> > > > > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > > > > 
> > > > > > 
> > > > > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > > > > 
> > > > > 
> > > > > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> > > > 
> > > > 
> > > > 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> > > > 连这点费用都不想承担，那你闭嘴吧！
> > > 
> > > 
> > > > > > > 你了解的比较少。
> > > > > > > 由于是支持长录音文件转录，音频文件可能会较大，直接使用http请求阿里云对于服务的可用性无法保证。所以使用OSS存储作为中转站就很自然了。
> > > > > > 
> > > > > > 
> > > > > > 对这种中转技术很感兴趣，请问有相关技术文章可以分享吗
> > > > > 
> > > > > 
> > > > > 与中转完全没关系，完全胡说八道，讯飞和腾讯就不需要单独开通对象存储OSS，接口可以直接上传音频，对象存储OSS，只是提供一个音频存储服务器，HTTP协议本身上传5G都没有问题，根本原因是：阿里要用户承担音频的存储成本，原因就这么简单。
> > > > 
> > > > 
> > > > 而且使用阿里云OSS作为临时存储，用完即删，基本不会产生存储费用，只会产生少量的流量费用。
> > > > 连这点费用都不想承担，那你闭嘴吧！
> > > 
> > > 
> > > 我和你说技术，你和我说费用，完全胡说八道，还假装一本正经的，这和中转有毛关系，上传阿里云对象存储OSS不是走http协议吗? 不要误导和胡说八道。
> > 
> > 
> > 你跑到我这儿来秀什么？抠字眼？我有说没有用http协议吗？我说的中转就是利用OSS最为临时存储，有问题吗？而且费用也是你自己提出来的。
> 
> 你是讨论问题还是吵架?自己搞不清楚，反而来怪我指出问题本质原因?

我吵架？你是什么语气？你是来讨论技术的吗？
你指出的本质是什么？就是所谓：“阿里要用户承担音频的存储成本” ？

这种音频转录的技术方案就是最合适的，远比讯飞的那种分片上传的要好，基本大部分服务商音频转录都是用的这种技术方案。
