### ISSUE TITLE
错误：录音文件识别失败

### ISSUE THREAD

**Issue by Andy766** [wxbool/video-srt-windows#30]
![image](https://user-images.githubusercontent.com/58882497/108533637-7c12ab00-72d9-11eb-8b65-f994fd96e109.png)
已经确认过 
Appkey没有填写错误
软件创建语音引擎时 已填写海外

**Comment by wtjfree** [comment]
类似的错误.这两天海外阿里云无法识别字幕了. 提示超时.

**Comment by wxbool** [comment]
下个版本修复
