### ISSUE TITLE
批量任务时（1个以上） 翻译请求失败 单个翻译正常

### ISSUE THREAD

**Issue by nikoedwards** [wxbool/video-srt-windows#31]
ps 感谢作者 
![给1](https://user-images.githubusercontent.com/76367747/109422682-8f2f2480-7a17-11eb-8c75-f9f11dd8dfd7.jpg)

**Comment by wxbool** [comment]
请使用百度翻译高级版的账号，标准版的并发数支持的很低，导致请求失败。
