### ISSUE TITLE
字幕获取，任务一直处在“提取音频文件”这个阶段

### ISSUE THREAD

**Issue by xiaoniaoyouhuajiang** [wxbool/video-srt-windows#33]
![image](https://user-images.githubusercontent.com/23737972/115712034-dc3fcf00-a3a6-11eb-8a6a-f6eb6dbcf35c.png)
一直卡着，没有继续进行，输入文件是一个mp4文件

**Comment by wxbool** [comment]
一般是媒体文件的格式问题
