### ISSUE TITLE
添加支持ChatGPT api的功能

### ISSUE THREAD

**Issue by LiMinghuaLiGan** [wxbool/video-srt-windows#56]
可以支持调用openai的api吗，网上类似的工具可以看出gpt-3.5的上下文理解能力好很多。

**Comment by Diaoxiaozhang** [comment]
同求

**Comment by wxbool** [comment]
目前维护的 videosrt pro 已增加 Chatgpt 翻译引擎，可以下载体验：

https://www.yuque.com/viggo-t7cdi/videosrt-pro/cpwtwl
